services:
  # Container Utama Laravel
  laravel.test:
    image: serversideup/php:8.4-fpm-nginx
    ports:
      - '8080:8080'
    volumes:
      - '.:/var/www/html'
    environment:
      - APP_ENV=local
      - DB_HOST=miniport-db
      - PHP_OPCACHE_ENABLE=0

      # Batas request Nginx
      - NGINX_CLIENT_MAX_BODY_SIZE=512M

      # Batas upload PHP
      - PHP_UPLOAD_MAX_FILE_SIZE=500M
      - PHP_POST_MAX_SIZE=512M

      # Resource dan waktu proses upload
      - PHP_MEMORY_LIMIT=768M
      - PHP_MAX_EXECUTION_TIME=600
      - PHP_MAX_INPUT_TIME=600
    networks:
      - miniport-network
    depends_on:
      - miniport-db
  # Container Database MySQL
  miniport-db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=miniport
    volumes:
      - 'miniport-mysql:/var/lib/mysql'
    networks:
      - miniport-network

  # Container MiniStack / LocalStack (AWS Emulator)
  ministack:
    image: localstack/localstack
    ports:
      - '4566:4566'
    environment:
      - SERVICES=s3,sqs,sns
    volumes:
      - "miniport-localstack:/var/lib/localstack"
    networks:
      - miniport-network

networks:
  miniport-network:
    driver: bridge

volumes:
  miniport-mysql:
    driver: local
  miniport-localstack:
    driver: local

